### PR TITLE
Create map and sidebar components

### PR DESCRIPTION
**Pull request by kellyi**
## Overview

This PR begins the app by adding map and sidebar components, styled roughly to match the wireframes.

I also started some Sass components, including one with color variables which I extracted from the wireframes.

40429c6 drops redux-act and immutability-helper, which we won't be using in the project.

Connects #2 

### Demo

screen shot 2018-07-16 at 3 20 30 pm

## Testing Instructions

- get, build, and serve this branch, then visit http://localhost:4567 and ensure the app loads as depicted above in both Chrome and IE11

### CODE REVIEW

**Comment by rajadain** [comment]
We should totally try to make it work first and optimize second, but just want to note that we're already at 4+ MB of JavaScript and a Lighthouse performance score of 11/100.

image

A lot of this will be remedied by deploying to Netlify which does many runtime optimizations (text compression, etc)

**Comment by rajadain** [comment]
+1 tested, no build errors and can see the sidebar, button, and map on both Chrome and IE11:

image

image

**Comment by kellyi** [comment]
> we're already at 4+ MB of JavaScript and a Lighthouse performance score of 11/100

If we'd like I can pull react-loadable in right away so the assets will be chunked. In general I think we should also drop the vendor bundle because it's including dependencies which may not ever get used.

Tried running cibuild to see what the production bundles looked like but cibuild is currently broken for the app template. I'll fix it in passing here.

Thanks for reviewing!

**Comment by kellyi** [comment]
Update: I fixed cibuild and this is what the output looks like:

```
Built at: 2018-7-16 19:59:52                                                                                                                                                 
                                Asset       Size  Chunks                    Chunk Names                                                                                      
vendor.bundle.68bf1710db9870f08e9a.js    399 KiB       0  [emitted]  [big]  vendor                                                                                           
   app.bundle.68bf1710db9870f08e9a.js    499 KiB       1  [emitted]  [big]  app                                                                                              
                           index.html  467 bytes          [emitted]                                                                                                          
Entrypoint app [big] = app.bundle.68bf1710db9870f08e9a.js                                                                                                                    
Entrypoint vendor [big] = vendor.bundle.68bf1710db9870f08e9a.js          
```

Still large but at least not 4mb.

**Comment by rajadain** [comment]
Much better! 👏

**Pull request merged**
